name = "Subspaces"
uuid = "922a6ab9-c04b-46bc-b8bf-400344129a3c"
authors = ["Dan Stahlke <dan@stahlke.org>"]
version = "0.1.0"

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
